spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
security:
  oauth2:
    client:
      clientId: 150279922178-fur6lba6e88ih3ssc5ssrfcfoi4v409r.apps.googleusercontent.com
      clientSecret: Fq4ozdA6wlYW8-KV4weiSbri
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
      preestabishedRedirectUri: http://localhost:8080/login
      registeredRedirectUri: http://localhost:8080/login
